CREATE DATABASE CharacterDatabase;

Use CharacterDatabase;

CREATE TABLE Characters 
(
ID INT PRIMARY KEY AUTO_INCREMENT,
Name TEXT NOT NULL,
Class TEXT NOT NULL,
Race TEXT NOT NULL,
Alignment TEXT NOT NULL,
Strength INT NOT NULL,
Dexterity INT NOT NULL,
Constitution INT NOT NULL,
Intelligence INT NOT NULL,
Wisdom INT NOT NULL,
Charisma INT NOT NULL,
CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
MODIFIED DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	
);
